version: "3.8"

services:
  auth_db:
    image: mysql:8.0
    container_name: auth_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - auth_db_data:/var/lib/mysql
    networks:
      - ecommerce_net
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uadmin", "-padmin"]
      interval: 10s
      timeout: 5s
      retries: 10

  auth_service:
    build:
      context: ./src/modules/auth_service
    container_name: auth_service
    ports:
      - "8000:8000"
    depends_on:
      auth_db:
        condition: service_healthy
    environment:
      DATABASE_URL: mysql+pymysql://admin:admin@auth_db:3306/auth_db
      SECRET_KEY: mi_clave_secreta
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    networks:
      - ecommerce_net
    restart: on-failure

  ecommerce_db:
    image: mysql:8.0
    container_name: ecommerce_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"
    volumes:
      - ecommerce_db_data:/var/lib/mysql
    networks:
      - ecommerce_net
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uadmin", "-padmin"]
      interval: 10s
      timeout: 5s
      retries: 10
  cart_service:
    build:
      context: ./src/modules/cart_service
    container_name: cart_service
    ports:
      - "8002:8000"
    depends_on:
      - auth_service
      - ecommerce_db
    environment:
      DATABASE_URL: mysql+pymysql://admin:admin@ecommerce_db:3306/ecommerce_db
      AUTH_SERVICE_URL: http://auth_service:8000/auth/verify-token
      SECRET_KEY: mi_clave_secreta
      ALGORITHM: HS256
    networks:
      - ecommerce_net
    restart: on-failure

  product_service:
    build:
      context: ./src/modules/product_service
    container_name: product_service
    ports:
      - "8001:8000"
    depends_on:
      ecommerce_db:
        condition: service_healthy
    environment:
      DATABASE_URL: mysql+pymysql://admin:admin@ecommerce_db:3306/ecommerce_db
    networks:
      - ecommerce_net
    restart: on-failure

  order_service:
    build:
      context: ./src/modules/order_service
    container_name: order_service
    ports:
      - "8003:8000"
    depends_on:
      - auth_service
      - cart_service
      - product_service
      - ecommerce_db
    environment:
      DATABASE_URL: mysql+pymysql://admin:admin@ecommerce_db:3306/ecommerce_db
      AUTH_SERVICE_URL: http://auth_service:8000/auth/verify-token
      CART_SERVICE_URL: http://cart_service:8000/api/cart
      PRODUCT_SERVICE_URL: http://product_service:8000/products
      SECRET_KEY: mi_clave_secreta
      ALGORITHM: HS256
    networks:
      - ecommerce_net
    restart: on-failure

volumes:
  auth_db_data:
  ecommerce_db_data:

networks:
  ecommerce_net:
